apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-api-deployment
  labels:
    app: salary-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salary-api
  template:
    metadata:
      labels:
        app: salary-api
    spec:
      containers:
      - name: salary-api
        image: 096803082364.dkr.ecr.ap-south-1.amazonaws.com/salary-api:746439ad
        ports:
        - containerPort: 8080

