apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-api-deployment
  labels:
    app: salary-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salary-api
  template:
    metadata:
      labels:
        app: salary-api
    spec:
      containers:
      - name: salary-api
        image: ghcr.io/navabshariff/salary-api:925342e4
        ports:
        - containerPort: 8080

